// HWA recorder - a console diagnostic for hwa_extension.js, independent of it.
// Generated by tools/build_recorder.js - edit the template, not tools/hwa_recorder.js.
//
// Paste the whole file into the DevTools console on the game tab. Until stopped it records:
//  - how often the game actually draws, against how often the browser offers a frame
//  - whether a pixel read right after the game's own frame ever comes back black
//  - which of the script's known screens match right now, as you move around the game
//  - every click on the canvas, yours and the macro's: coordinates and the colour under it
//  - unknown screens (popups and the like) as a coarse colour grid
//  - #gameLoader, canvas size and position, tab visibility, WebGL context loss, page errors, memory
// The log is kept in localStorage, so after a page reload paste the file again and it carries on.
// Controls: the panel in the bottom-left corner, or hwaRec.mark('text') / .dump() / .stop() / .clear()
(() => {
    'use strict'
    if (window.hwaRec) window.hwaRec.stop()

    const SCREENS = {
        screenHome: [{"x":0.647452,"y":0.907678,"color":[236,237,200]},{"x":0.883876,"y":0.053931,"color":[254,255,97]}],
        screenGuild: [{"x":0.273832,"y":0.612474,"color":[72,39,0]},{"x":0.241437,"y":0.297075,"color":[213,21,26]}],
        screenLvl1: [{"x":0.695023,"y":0.10583,"color":[226,226,235],"threshold":20},{"x":0.274401,"y":0.193548,"color":[77,6,11]},{"x":0.19337,"y":0.209677,"color":[47,55,64]},{"x":0.837937,"y":0.211694,"color":[49,49,65]}],
        screenLvl234: [{"x":0.880535,"y":0.194698,"color":[60,37,65]},{"x":0.5,"y":0.104563,"color":[232,233,240]},{"x":0.52548,"y":0.156307,"color":[25,32,76]},{"x":0.642439,"y":0.211152,"color":[49,49,65]},{"x":0.195489,"y":0.211152,"color":[56,52,69]},{"x":0.273727,"y":0.251584,"color":[35,43,60]},{"x":0.274884,"y":0.228771,"color":[94,127,151]}],
        screenLvl789: [{"x":0.5,"y":0.104563,"color":[232,233,240]},{"x":0.52548,"y":0.156307,"color":[25,32,76]},{"x":0.642439,"y":0.211152,"color":[49,49,65]},{"x":0.792818,"y":0.207661,"color":[56,52,69]}],
        screenLvl5: [{"x":0.314815,"y":0.107098,"color":[235,234,241]},{"x":0.340852,"y":0.117916,"color":[24,33,78]},{"x":0.162072,"y":0.211152,"color":[49,49,65]},{"x":0.455305,"y":0.211152,"color":[49,49,65]},{"x":0.729745,"y":0.479721,"color":[135,75,0],"threshold":20}],
        screenFloor1Final: [{"x":0.3163664839467502,"y":0.1320754716981132,"color":[18,21,26]},{"x":0.160401,"y":0.209324,"color":[49,49,66]},{"x":0.457811,"y":0.209324,"color":[49,49,66]},{"x":0.649958,"y":0.300731,"color":[51,54,60]}],
        screenLvl6: [{"x":0.314815,"y":0.107098,"color":[235,234,241]},{"x":0.340852,"y":0.117916,"color":[24,33,78]},{"x":0.725982,"y":0.19287,"color":[76,6,11]},{"x":0.726273,"y":0.173004,"color":[68,77,94]}],
        screenLvl0: [{"x":0.695023,"y":0.10583,"color":[226,226,235],"threshold":20},{"x":0.669429,"y":0.114919,"color":[31,38,86]},{"x":0.349908,"y":0.298387,"color":[49,54,60]},{"x":0.197974,"y":0.294355,"color":[52,58,64]},{"x":0.277164,"y":0.477823,"color":[144,78,0],"threshold":20}],
        screenFloor2Final: [{"x":0.6985121378230227,"y":0.14408233276157806,"color":[20,22,28]},{"x":0.274401,"y":0.181452,"color":[57,70,93]},{"x":0.838858,"y":0.21371,"color":[49,49,65]}],
        popupOneRoomSelection: [{"x":0.715877,"y":0.093496,"color":[242,189,106]},{"x":0.714699,"y":0.098226,"color":[241,192,102]},{"x":0.495396,"y":0.106855,"color":[97,49,0]},{"x":0.558011,"y":0.633065,"color":[176,207,248]},{"x":0.494475,"y":0.891129,"color":[20,16,4]}],
        popupTwoRoomsSelection: [{"x":0.876509,"y":0.099593,"color":[241,196,107]},{"x":0.876736,"y":0.102028,"color":[244,203,113]},{"x":0.500418,"y":0.80713,"color":[16,14,4]},{"x":0.370092,"y":0.63894,"color":[179,204,245]},{"x":0.494475,"y":0.891129,"color":[20,16,4]}],
        screenBattlefield: [{"x":0.039352,"y":0.047529,"color":[234,203,151]},{"x":0.971216,"y":0.050813,"color":[243,197,107]}],
        popupBattleResult: [{"x":0.60083,"y":0.127563,"color":[137,1,0]},{"x":0.497911,"y":0.792505,"color":[46,125,192]}],
        popupBattleResult5Titans: [{"x":0.544104,"y":0.825203,"color":[51,132,202],"threshold":30},{"x":0.402971,"y":0.825203,"color":[55,142,216],"threshold":30},{"x":0.54039,"y":0.365854,"color":[33,28,41],"threshold":10},{"x":0.620241,"y":0.357724,"color":[33,28,41],"threshold":10},{"x":0.542247,"y":0.369919,"color":[33,28,41],"threshold":10}],
        popupFloorReward: [{"x":0.5,"y":0.5,"color":[22,12,8]},{"x":0.387636,"y":0.403108,"color":[78,6,11]},{"x":0.258145,"y":0.264168,"color":[22,12,8]},{"x":0.634921,"y":0.567642,"color":[255,252,109]}],
        screenFrontier: [{"x":0.04919,"y":0.434094,"color":[237,209,158]}],
        screenBattlePrep: [{"x":0.841435,"y":0.766195,"color":[65,158,28]}],
        screenLose: [{"x":0.497106,"y":0.251584,"color":[180,14,36]}],
        screenReorderTeams: [{"x":0.499421,"y":0.004436,"color":[3,6,9]}],
        screenExpeditionOpened: [{"x":0.721644,"y":0.143219,"color":[24,12,8]}],
        screenValkyrieGift: [{"x":0.659722,"y":0.903676,"color":[73,158,22]}],
        screenHydraNoMoreFairies: [{"x":0.823495,"y":0.067807,"color":[30,15,20]}],
        screenTowerChestAvailable: [{"x":0.638889,"y":0.731939,"color":[69,166,31]}],
        screenTowerRewardPopup: [{"x":0.711806,"y":0.900507,"color":[68,165,30]}],
        screenCampAttackButton: [{"x":0.659722,"y":0.493663,"color":[255,253,239]}],
        screenCampBattleTransition: [{"x":0.5,"y":0.5,"color":[0,0,0]}],
        screenCampPopupAttackButton: [{"x":0.460648,"y":0.756654,"color":[56,146,0]}],
        screenCampBattleEnd: [{"x":0.860532,"y":0.867554,"color":[92,192,35]}],
        screenCampSearchClosed: [{"x":0.854167,"y":0.527883,"color":[36,48,67]}],
        screenChestRewardPopup: [{"x":0.381366,"y":0.050697,"color":[255,250,187]}],
        screenFreeChestAvailable: [{"x":0.409144,"y":0.857414,"color":[169,255,190]}]
    }

    const KEY = 'hwaRecLog'
    const MAX_LINES = 4000
    const STATS_EVERY_MS = 5000
    const SCREEN_EVERY_MS = 1000
    const BLACK_CHECK_EVERY = 10              // game frames between black checks - every read stalls the GPU
    const BLACK_CHECK_POINTS = [[0.5, 0.5], [0.25, 0.3], [0.75, 0.3], [0.25, 0.8], [0.75, 0.8]]
    const DEFAULT_THRESHOLD = 15
    const GRID_COLS = 6, GRID_ROWS = 4

    // ---------- log ----------
    let lines = []
    try { lines = JSON.parse(localStorage.getItem(KEY)) || [] } catch (e) {}
    const startedAt = Date.now()
    let persistTimer = null

    function stamp() {
        const d = new Date()
        return d.toLocaleTimeString('ru-RU', { hour12: false }) + '.' + String(d.getMilliseconds()).padStart(3, '0')
    }
    function add(kind, text) {
        lines.push(stamp() + ' [' + kind + '] ' + text)
        if (lines.length > MAX_LINES) lines.splice(0, lines.length - MAX_LINES)
        if (persistTimer == null) persistTimer = setTimeout(persist, 1000)
    }
    function persist() {
        persistTimer = null
        try { localStorage.setItem(KEY, JSON.stringify(lines)) } catch (e) {}
    }

    const cleanups = []
    function on(target, type, fn, opts) {
        target.addEventListener(type, fn, opts)
        cleanups.push(() => target.removeEventListener(type, fn, opts))
    }

    // ---------- page state ----------
    let canvas = document.getElementById('gameCanvas')
    if (!canvas) { console.log('HWA recorder: на странице нет #gameCanvas'); return }
    const loader = document.getElementById('gameLoader')
    const loaderState = () => loader ? getComputedStyle(loader).display : 'нет элемента'

    function geometry() {
        const r = canvas.getBoundingClientRect()
        return 'канвас ' + canvas.width + 'x' + canvas.height + ', на экране ' + Math.round(r.width) + 'x' + Math.round(r.height) +
            ' в ' + Math.round(r.left) + ',' + Math.round(r.top) + ', окно ' + innerWidth + 'x' + innerHeight + ', dpr ' + devicePixelRatio
    }

    // Asking for a context before the game has made its own would create one, so wait for the loader.
    let gl = null
    function ensureGl() {
        if (gl || loaderState() !== 'none') return
        gl = canvas.getContext('webgl2')
        add('gl', gl ? 'контекст webgl2, preserveDrawingBuffer: ' + (gl.getContextAttributes() || {}).preserveDrawingBuffer
                     : 'webgl2-контекста нет - игра рисует чем-то другим')
    }

    // ---------- reading the screen ----------
    // Always the default framebuffer, whatever the game left bound for its own work.
    function withScreenBound(fn) {
        const readFramebuffer = gl.getParameter(gl.READ_FRAMEBUFFER_BINDING)
        const packBuffer = gl.getParameter(gl.PIXEL_PACK_BUFFER_BINDING)
        if (readFramebuffer) gl.bindFramebuffer(gl.READ_FRAMEBUFFER, null)
        if (packBuffer) gl.bindBuffer(gl.PIXEL_PACK_BUFFER, null)
        try { return fn() } finally {
            if (packBuffer) gl.bindBuffer(gl.PIXEL_PACK_BUFFER, packBuffer)
            if (readFramebuffer) gl.bindFramebuffer(gl.READ_FRAMEBUFFER, readFramebuffer)
        }
    }

    const px = new Uint8Array(4)
    function readPoints(points) {
        return withScreenBound(() => points.map(([fx, fy]) => {
            const x = Math.min(canvas.width - 1, Math.max(0, Math.floor(fx * canvas.width)))
            const y = Math.min(canvas.height - 1, Math.max(0, Math.floor(fy * canvas.height)))
            gl.readPixels(x, canvas.height - 1 - y, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, px)
            return [px[0], px[1], px[2]]
        }))
    }

    // one big read is far cheaper than a hundred small ones: each read is a round trip to the GPU
    function grabFrame() {
        const w = canvas.width, h = canvas.height
        const buf = new Uint8Array(w * h * 4)
        withScreenBound(() => gl.readPixels(0, 0, w, h, gl.RGBA, gl.UNSIGNED_BYTE, buf))
        return {
            at(fx, fy) {
                const x = Math.min(w - 1, Math.max(0, Math.floor(fx * w)))
                const y = Math.min(h - 1, Math.max(0, Math.floor(fy * h)))
                const i = ((h - 1 - y) * w + x) * 4
                return [buf[i], buf[i + 1], buf[i + 2]]
            }
        }
    }

    const isBlack = c => c[0] === 0 && c[1] === 0 && c[2] === 0
    const hex = c => '#' + c.map(v => v.toString(16).padStart(2, '0')).join('')

    // ---------- game frames ----------
    // The first draw call of a frame queues a microtask; it runs once the game has finished that
    // frame and before the browser presents it - the one moment the drawing buffer holds a picture.
    const stats = { browserFrames: 0, gameFrames: 0, draws: 0, blackChecks: 0, black: 0 }
    const endOfFrameJobs = []
    let frameOpen = false, drawsInFrame = 0, gameFrameNo = 0

    function onGameFrameEnd() {
        frameOpen = false
        stats.gameFrames++
        stats.draws += drawsInFrame
        drawsInFrame = 0
        gameFrameNo++
        if (!gl) return
        if (gameFrameNo % BLACK_CHECK_EVERY === 0) {
            stats.blackChecks++
            if (readPoints(BLACK_CHECK_POINTS).every(isBlack)) stats.black++
        }
        for (const job of endOfFrameJobs.splice(0)) {
            try { job() } catch (e) { add('error', 'задача регистратора: ' + e.message) }
        }
    }

    const glProto = WebGL2RenderingContext.prototype
    for (const name of ['drawElements', 'drawArrays', 'drawElementsInstanced', 'drawArraysInstanced', 'drawRangeElements', 'blitFramebuffer']) {
        const original = glProto[name]
        if (typeof original !== 'function') continue
        glProto[name] = function (...args) {
            const result = original.apply(this, args)
            if (this === gl) {
                drawsInFrame++
                if (!frameOpen) { frameOpen = true; queueMicrotask(onGameFrameEnd) }
            }
            return result
        }
        cleanups.push(() => { glProto[name] = original })
    }

    let stopped = false
    function browserFrame() {
        if (stopped) return
        stats.browserFrames++
        requestAnimationFrame(browserFrame)
    }
    requestAnimationFrame(browserFrame)

    // ---------- wasm heap, caught on its next growth ----------
    let wasmMemory = null
    const originalGrow = WebAssembly.Memory.prototype.grow
    WebAssembly.Memory.prototype.grow = function (pages) {
        wasmMemory = this
        return originalGrow.call(this, pages)
    }
    cleanups.push(() => { WebAssembly.Memory.prototype.grow = originalGrow })

    function memoryText() {
        const parts = []
        try { if (wasmMemory) parts.push('wasm ' + Math.round(wasmMemory.buffer.byteLength / 1048576) + ' МБ') } catch (e) {}
        if (performance.memory) parts.push('JS ' + Math.round(performance.memory.usedJSHeapSize / 1048576) + ' МБ')
        return parts.join(', ')
    }

    // ---------- screens ----------
    const gameFpsSamples = []
    const screensSeen = {}
    let lastScreenKey = null, lastGrid = null, screenBusy = false
    let currentScreen = '...'

    function evaluateScreens() {
        if (!gl) return
        const frame = grabFrame()
        const results = Object.entries(SCREENS).map(([name, points]) => {
            let ok = 0
            for (const p of points) {
                const c = frame.at(p.x, p.y)
                const t = p.threshold ?? DEFAULT_THRESHOLD
                if (p.color.every((v, k) => Math.abs(v - c[k]) <= t)) ok++
            }
            return { name, ok, n: points.length }
        })

        const full = results.filter(r => r.ok === r.n)
        let text, key
        if (full.length) {
            text = 'опознан: ' + full.map(r => r.name + ' (' + r.ok + '/' + r.n + ')').join(', ')
            key = full.map(r => r.name).join(',')
            currentScreen = full.map(r => r.name).join(', ')
        } else {
            const near = results.filter(r => r.ok > 0).sort((a, b) => b.ok / b.n - a.ok / a.n).slice(0, 3)
            text = 'не опознан' + (near.length ? '; ближе всего ' + near.map(r => r.name + ' ' + r.ok + '/' + r.n).join(', ') : '')
            key = 'none'
            currentScreen = 'не опознан'
        }

        if (key !== lastScreenKey) {
            lastScreenKey = key
            add('screen', text)
            for (const r of full) screensSeen[r.name] = (screensSeen[r.name] || 0) + 1
        }

        // unknown screens get a colour grid, so a popup or a new screen can be told apart later
        if (!full.length) {
            const grid = []
            for (let row = 0; row < GRID_ROWS; row++) {
                for (let col = 0; col < GRID_COLS; col++) {
                    grid.push(frame.at((col + 0.5) / GRID_COLS, (row + 0.5) / GRID_ROWS))
                }
            }
            const changed = !lastGrid || grid.reduce((sum, c, i) => sum + Math.abs(c[0] - lastGrid[i][0]) + Math.abs(c[1] - lastGrid[i][1]) + Math.abs(c[2] - lastGrid[i][2]), 0) / grid.length > 40
            if (changed) {
                lastGrid = grid
                add('grid', 'сетка ' + GRID_COLS + 'x' + GRID_ROWS + ' (строки сверху вниз): ' + grid.map(hex).join(' '))
            }
        } else {
            lastGrid = null
        }
    }

    const screenTimer = setInterval(() => {
        ensureGl()
        if (!gl || screenBusy || document.hidden) return
        screenBusy = true
        endOfFrameJobs.push(() => { screenBusy = false; evaluateScreens() })
    }, SCREEN_EVERY_MS)
    cleanups.push(() => clearInterval(screenTimer))

    // ---------- periodic stats ----------
    const statsTimer = setInterval(() => {
        const sec = STATS_EVERY_MS / 1000
        const browserFps = Math.round(stats.browserFrames / sec)
        const gameFps = Math.round(stats.gameFrames / sec)
        gameFpsSamples.push(gameFps)
        add('stats', 'браузер ' + browserFps + ' к/с, игра рисует ' + gameFps + ' к/с' +
            (stats.browserFrames ? ' (' + Math.round(stats.gameFrames / stats.browserFrames * 100) + '% кадров)' : '') +
            ', отрисовок на кадр ' + (stats.gameFrames ? Math.round(stats.draws / stats.gameFrames) : 0) +
            ', чёрных чтений после кадра игры ' + stats.black + '/' + stats.blackChecks +
            (document.hidden ? ', вкладка скрыта' : '') + (memoryText() ? ', ' + memoryText() : ''))
        Object.keys(stats).forEach(k => { stats[k] = 0 })
        updatePanel()
    }, STATS_EVERY_MS)
    cleanups.push(() => clearInterval(statsTimer))

    // ---------- clicks: yours are trusted pointer events, the macro dispatches plain mouse events ----------
    function recordClick(e, who) {
        const r = canvas.getBoundingClientRect()
        const fx = (e.clientX - r.left) / r.width
        const fy = (e.clientY - r.top) / r.height
        const point = { x: Number(fx.toFixed(6)), y: Number(fy.toFixed(6)) }
        const queuedAt = performance.now()
        endOfFrameJobs.push(() => {
            const [color] = readPoints([[fx, fy]])
            add('click', who + ' ' + JSON.stringify({ ...point, color }) + ', цвет прочитан через ' + Math.round(performance.now() - queuedAt) + ' мс')
        })
    }
    on(canvas, 'pointerdown', e => { if (e.isTrusted) recordClick(e, 'ты') }, true)
    on(canvas, 'mousedown', e => { if (!e.isTrusted) recordClick(e, 'макрос') }, true)

    // ---------- DOM, visibility, context, errors ----------
    let lastGeometry = geometry()
    function checkGeometry(reason) {
        const g = geometry()
        if (g !== lastGeometry) { lastGeometry = g; add('canvas', reason + ': ' + g) }
    }
    const canvasObserver = new MutationObserver(() => checkGeometry('атрибуты канваса'))
    canvasObserver.observe(canvas, { attributes: true, attributeFilter: ['width', 'height', 'style', 'class'] })
    cleanups.push(() => canvasObserver.disconnect())
    on(window, 'resize', () => checkGeometry('размер окна'))

    if (canvas.parentNode) {
        const parentObserver = new MutationObserver(() => {
            const current = document.getElementById('gameCanvas')
            if (current !== canvas) add('canvas', current ? 'канвас заменён новым элементом' : 'канвас удалён со страницы')
        })
        parentObserver.observe(canvas.parentNode, { childList: true })
        cleanups.push(() => parentObserver.disconnect())
    }

    if (loader) {
        let lastLoader = loaderState()
        const loaderObserver = new MutationObserver(() => {
            const s = loaderState()
            if (s !== lastLoader) { add('loader', lastLoader + ' -> ' + s); lastLoader = s }
        })
        loaderObserver.observe(loader, { attributes: true, attributeFilter: ['style', 'class'] })
        cleanups.push(() => loaderObserver.disconnect())
    }

    on(document, 'visibilitychange', () => add('tab', document.hidden ? 'вкладка скрыта' : 'вкладка снова видна'))
    on(window, 'blur', () => add('tab', 'окно потеряло фокус'))
    on(window, 'focus', () => add('tab', 'окно получило фокус'))
    on(canvas, 'webglcontextlost', () => add('gl', 'КОНТЕКСТ ПОТЕРЯН'))
    on(canvas, 'webglcontextrestored', () => add('gl', 'контекст восстановлен'))
    on(window, 'error', e => { if (e.message) add('error', String(e.message).slice(0, 300)) })
    on(window, 'unhandledrejection', e => add('error', 'promise: ' + String(e.reason).slice(0, 300)))

    // ---------- panel ----------
    const panel = document.createElement('div')
    Object.assign(panel.style, {
        position: 'fixed', left: '8px', bottom: '8px', zIndex: '2147483647', display: 'flex', gap: '6px', alignItems: 'center',
        padding: '4px 8px', background: 'rgba(16,20,24,0.85)', color: '#cfe', font: '12px monospace', border: '1px solid #4f8', borderRadius: '6px'
    })
    const panelText = document.createElement('span')
    panel.appendChild(panelText)
    function button(label, fn) {
        const b = document.createElement('button')
        b.textContent = label
        Object.assign(b.style, { font: '12px sans-serif', padding: '2px 6px', cursor: 'pointer' })
        b.addEventListener('click', e => { e.stopPropagation(); fn() })
        panel.appendChild(b)
    }
    button('Отметка', () => mark(prompt('Что сейчас происходит?') || ''))
    button('Выгрузить', () => dump())
    button('Стоп', () => stop())
    document.body.appendChild(panel)
    cleanups.push(() => panel.remove())

    function updatePanel() {
        const s = Math.round((Date.now() - startedAt) / 1000)
        panelText.textContent = '● REC ' + Math.floor(s / 60) + ':' + String(s % 60).padStart(2, '0') +
            ' | игра ' + (gameFpsSamples.length ? gameFpsSamples[gameFpsSamples.length - 1] : '?') + ' к/с | ' + currentScreen
    }
    const panelTimer = setInterval(updatePanel, 1000)
    cleanups.push(() => clearInterval(panelTimer))

    // ---------- commands ----------
    function mark(text) {
        if (text) add('mark', text)
    }

    function summary() {
        const sorted = gameFpsSamples.slice().sort((a, b) => a - b)
        const median = sorted.length ? sorted[Math.floor(sorted.length / 2)] : '?'
        return [
            '=== HWA recorder, сводка этого запуска ===',
            'запись: ' + Math.round((Date.now() - startedAt) / 1000) + ' с, строк в журнале: ' + lines.length,
            'игра рисует, к/с: мин ' + (sorted[0] ?? '?') + ', медиана ' + median + ', макс ' + (sorted[sorted.length - 1] ?? '?'),
            'опознанные экраны: ' + (Object.entries(screensSeen).map(([k, v]) => k + ' x' + v).join(', ') || 'нет'),
            geometry(),
            '==========================================='
        ].join('\n')
    }

    function dump() {
        persist()
        const text = summary() + '\n' + lines.join('\n')
        try { copy(text) } catch (e) {}
        const box = document.createElement('textarea')
        box.value = text
        Object.assign(box.style, {
            position: 'fixed', left: '5%', top: '5%', width: '90%', height: '80%', zIndex: '2147483647',
            font: '11px monospace', background: '#101418', color: '#8fe08f', border: '2px solid #4f8'
        })
        const close = document.createElement('button')
        close.textContent = 'Закрыть'
        Object.assign(close.style, { position: 'fixed', right: '6%', top: '86%', zIndex: '2147483647', padding: '8px 20px' })
        close.onclick = () => { box.remove(); close.remove() }
        document.body.appendChild(box)
        document.body.appendChild(close)
        box.focus()
        box.select()
    }

    function stop() {
        if (stopped) return
        stopped = true
        add('stop', 'запись остановлена')
        persist()
        cleanups.splice(0).forEach(fn => { try { fn() } catch (e) {} })
        delete window.hwaRec
        console.log('HWA recorder остановлен. Журнал сохранён, выгрузить: вставь регистратор снова и нажми «Выгрузить»')
    }

    function clear() {
        lines = []
        persist()
        add('start', 'журнал очищен')
    }

    window.hwaRec = { mark, dump, stop, clear }

    if (lines.length) add('start', '----- новый запуск (страница перезагружалась или регистратор вставлен заново) -----')
    add('start', 'запись начата; ' + geometry() + '; загрузчик: ' + loaderState() + '; вкладка ' + (document.hidden ? 'скрыта' : 'видна') +
        '; ' + ((navigator.userAgent.match(/Chrome\/[\d.]+/) || [''])[0]) + '; эталонов экранов: ' + Object.keys(SCREENS).length)
    ensureGl()
    updatePanel()
    console.log('HWA recorder запущен. Панель внизу слева; hwaRec.mark("текст"), hwaRec.dump(), hwaRec.stop(), hwaRec.clear()')
})()
